BEGIN TRANSACTION;
CREATE TABLE `Regions` (
	`RegionID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Name`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE "RegionTravelTimes" (
	`Point1`	INTEGER NOT NULL,
	`Point2`	INTEGER NOT NULL,
	`BaseTime`	INTEGER NOT NULL,
	`RegionTravelTimeID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY(`Point1`) REFERENCES `Regions`(`RegionID`),
	FOREIGN KEY(`Point2`) REFERENCES `Regions`(`RegionID`)
);
CREATE TABLE `PlayerStatus` (
	`CurrentMoney`	INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE "Perks" (
	`PerkId`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`AgentID`	INTEGER NOT NULL,
	`Type`	TEXT,
	`Strength`	REAL,
	FOREIGN KEY(`AgentID`) REFERENCES `Agents`(`AgentId`)
);
CREATE TABLE "Passports" (
	`PassportId`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`PersonName`	TEXT NOT NULL UNIQUE,
	`Heat`	INTEGER NOT NULL DEFAULT 0,
	`Owned`	INTEGER NOT NULL DEFAULT 0,
	`Price`	INTEGER DEFAULT 0
);
CREATE TABLE "OpenContracts" (
	`OpenContractID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Origin`	TEXT NOT NULL,
	`Destination`	TEXT NOT NULL,
	`Value`	INTEGER DEFAULT 0,
	`Duration`	INTEGER NOT NULL DEFAULT 1,
	`Expiration`	INTEGER,
	`Risk`	INTEGER,
	FOREIGN KEY(`Origin`) REFERENCES `Cities`(`CityID`),
	FOREIGN KEY(`Destination`) REFERENCES `Cities`(`CityID`)
);
CREATE TABLE "Jobs" (
	`JobId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`AgentId`	INTEGER NOT NULL,
	`Complete`	int NOT NULL DEFAULT 0,
	`Origin`	INTEGER NOT NULL,
	`Destination`	INTEGER NOT NULL,
	`Value`	numeric NOT NULL,
	`ETA`	INTEGER,
	`PassportId`	INTEGER,
	`StartTime`	INTEGER NOT NULL,
	FOREIGN KEY(`AgentId`) REFERENCES `Agents`(`AgentId`),
	FOREIGN KEY(`PassportId`) REFERENCES `Passports`(`PassportId`)
);
CREATE TABLE "Cities" (
	`CityID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`RegionID`	INTEGER NOT NULL DEFAULT 1,
	`Name`	TEXT NOT NULL DEFAULT 'none' UNIQUE,
	`Security`	INTEGER,
	FOREIGN KEY(`RegionID`) REFERENCES `Regions`(`RegionId`)
);
CREATE TABLE "Agents" (
	`AgentId`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`AgentName`	TEXT NOT NULL UNIQUE,
	`Heat`	INTEGER NOT NULL DEFAULT 0,
	`Owned`	INTEGER NOT NULL DEFAULT 1,
	`Price`	INTEGER DEFAULT 0,
	`Level`	INTEGER NOT NULL DEFAULT 1,
	`Experience`	INTEGER NOT NULL DEFAULT 0,
	`MaxHeat`	INTEGER DEFAULT 100
);
COMMIT;
